apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-forge-deployment
  namespace: spring-forge-namespace
  labels:
    app: spring-forge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-forge
  template:
    metadata:
      labels:
        app: spring-forge
    spec:
      containers:
        - name: spring-forge
          image: yllub/spring-forge:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
