apiVersion: v1
kind: ResourceQuota
metadata:
  name: spring-forge-quota
  namespace: spring-forge-namespace
spec:
  hard:
    requests.cpu: "2"       # Total CPU requests across all Pods
    requests.memory: 4Gi    # Total memory requests across all Pods
    limits.cpu: "4"         # Total CPU limits across all Pods
    limits.memory: 8Gi      # Total memory limits across all Pods
    pods: "10"              # Maximum number of Pods in the namespace
