apiVersion: v1
kind: Service
metadata:
  name: spring-forge-service
  namespace: spring-forge-namespace
spec:
  selector:
    app: spring-forge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
